### ISSUE TITLE
Resource.Id [placeholder title]

### ISSUE THREAD

**Issue by brendanzagaeski** [xamarin/xamarin-android#3702]
### Background context

*rsgrey commented on Sep 26* <https://github.com/xamarin/xamarin-android/issues/3494#issuecomment-535468674>

> Hello!
> The problem is actual!
> Xamarin.Android SDK 10.0.0.43
> Visual Studio 2019 version 16.3.1

* * *

*brendanzagaeski commented on Sep 26* <https://github.com/xamarin/xamarin-android/issues/3494#issuecomment-535596240>

> rsgrey, note that errors like this can also occur if the Xamarin.Android.Support NuGet packages have not yet been restored successfully into a project. If you are stuck on similar errors, then when you get a chance, you can report a [new issue](https://github.com/xamarin/xamarin-android/issues/new), if possible attaching either a zipped up example project that demonstrates the problem or the [diagnostic MSBuild output](https://docs.microsoft.com/visualstudio/ide/how-to-view-save-and-configure-build-log-files?view=vs-2019#to-change-the-amount-of-information-included-in-the-build-log) from your project, and the team can take a look. Thanks in advance!

* * *

*rsgrey commented on Sep 27* <https://github.com/xamarin/xamarin-android/issues/3494#issuecomment-536010726>

> [log.txt](https://github.com/xamarin/xamarin-android/files/3663743/log.txt)
> 
> Hello.
> I attached a log file

* * *

### Steps to reproduce

(Not yet described.)

### Actual behavior

The build fails due to a mismatch between the resource IDs that are requested in the C# files and the resource IDs that are available in the generated *Resource.designer.cs* file:

```
BaseAbstract.cs(60,43,60,54): error CS0117: 'Resource.Id' does not contain a definition for 'contentView'
BaseAbstract.cs(61,43,61,52): error CS0117: 'Resource.Id' does not contain a definition for 'emptyView'
2View.cs(52,99,52,110): error CS0117: 'Resource.Id' does not contain a definition for 'contentView'
2View.cs(53,91,53,104): error CS0117: 'Resource.Id' does not contain a definition for 'btn_container'
2View.cs(73,99,73,110): error CS0117: 'Resource.Id' does not contain a definition for 'contentView'
2View.cs(74,91,74,104): error CS0117: 'Resource.Id' does not contain a definition for 'btn_container'
2View.cs(94,74,94,82): error CS0117: 'Resource.Id' does not contain a definition for 'btn_next'
1View.cs(73,99,73,110): error CS0117: 'Resource.Id' does not contain a definition for 'contentView'
1View.cs(74,91,74,104): error CS0117: 'Resource.Id' does not contain a definition for 'btn_container'
1View.cs(94,99,94,110): error CS0117: 'Resource.Id' does not contain a definition for 'contentView'
1View.cs(95,91,95,104): error CS0117: 'Resource.Id' does not contain a definition for 'btn_container'
1View.cs(116,69,116,77): error CS0117: 'Resource.Id' does not contain a definition for 'step_bar'
1View.cs(117,74,117,82): error CS0117: 'Resource.Id' does not contain a definition for 'btn_next'
```

### Version Information

Xamarin.Android 10.0.0.43
Visual Studio 2019 version 16.3.1

**Comment by brendanzagaeski** [comment]
@rsgrey, thanks for the log file! My first guess is that these resource IDs might be defined in Android XML resource files in your app or your custom libraries (since `btn_container` [doesn't seem to be present in any of the Android platform or support libraries](https://www.google.com/search?q="btn_container"+site%3Ahttps%3A%2F%2Fandroid.googlesource.com)).

  * `contentView`
  * `emptyView`
  * `btn_container`
  * `btn_next`
  * `step_bar`

### Next steps

 1. Do you by chance have any additional details you can share about where these missing resource IDs are defined? Do any of your Android XML resource files contain these IDs?

    If you can share the names of the XML files and if possible also attach the XML files that contain these resource IDs, that would be perfect.

 2. Do the errors go away if you check and then re-uncheck the **Use incremental packaging system (aapt2)** setting in the Visual Studio project property pages, save the change, and then clean and rebuild the project? If so, do the errors come back if you re-enable **Use incremental packaging system (aapt2)**?

Thanks in advance!

**Comment by rsgrey** [comment]
@brendanzagaeski 
Project build and work in Visual Studio 2017 build 15.9.16 and worked in Visual Studio 2019 build 16.2.5

Resource.designer.cs have this ids:
```
// aapt resource value: 0x7F020182
public const int contentView = 2130837890;
// aapt resource value: 0x7F020187
public const int emptyView = 2130837895;
// aapt resource value: 0x7F020186
public const int btn_next = 2130837894;
// aapt resource value: 0x7F020185
public const int btn_container = 2130837893;
// aapt resource value: 0x7F020184
public const int step_bar = 2130837892;
```


1. Add xml file:
```
<FrameLayout 
	xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
	android:fitsSystemWindows="true">
    <RelativeLayout 
	    android:id="@+id/contentView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
    >
	
	<android.support.v4.widget.NestedScrollView 
		android:id="@+id/scroll"
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		android:layout_alignParentTop="true">

		<LinearLayout
			android:layout_width="match_parent"
			android:layout_height="wrap_content"
			android:orientation="vertical">

			<AppAndroid.Elements.StepBar.StepBarElement 
				android:layout_width="match_parent"
				android:layout_height="100dp"
				android:id="@+id/step_bar"
			/>

			<FrameLayout 
				android:id="@+id/container_sections" 
				android:layout_width="match_parent"
				android:layout_height="wrap_content"
			/>



			<FrameLayout
				android:id="@+id/btn_container"
				android:layout_width="match_parent"
				android:layout_height="56dp"
			/>

		</LinearLayout>
	</android.support.v4.widget.NestedScrollView>

	<AppAndroid.Elements.BottomButtonElement 
		android:id="@+id/btn_next"
		app:type="Secondary"
		android:layout_width="match_parent"
		android:layout_height="56dp"
		android:layout_alignParentBottom="true"
	/>
    </RelativeLayout>
    
    <include android:id="@+id/emptyView"  android:visibility="gone" layout="@layout/template_orderA_01_empty" />
</FrameLayout>
```
2. These actions did not solve the problem

**Comment by brendanzagaeski** [comment]
@rsgrey, thanks! Just for completeness, if you can share it, what is the file name of that XML file? I'm curious to see if there is anything unusual in the build log that mentions that XML file.

**Comment by rsgrey** [comment]
@brendanzagaeski, template_orderA_01.axml

**Comment by rsgrey** [comment]
Hello. You didn't find a possible reason?

**Comment by brendanzagaeski** [comment]
Apologies for the slow reply. I got a chance to look at the log file, and I noticed one potential source of trouble.

The project currently contains the following two resource items:

  * *Resources\layout\template_orderA_01.axml*, `LogicalName=layout\template_orderA_01.axml`

  * *Resources\layout\template_orderA_01.xml*,  `LogicalName=layout\template_orderA_01.xml`

It looks like the build process (in particular the `CopyIfChanged` task during the `_GenerateAndroidResourceDir` target) is currently silently copying the *.xml* file over the contents of the *.axml* file without a warning. It copies both files into the same intermediate output location:

*obj\Debug\90\res\layout\template_ordera_01.xml*

I'll do a bit of local testing to see if I can reproduce the problem based on that information.

## Possible workaround

There's a chance that removing the *template_orderA_01.axml* file or the *template_orderA_01.xml* file and then cleaning the project (or maybe manually deleting the *bin* and *obj* directories) might help resolve this issue. If you get a chance to try that, feel free to reply back with whether it helps or not.

**Comment by rsgrey** [comment]
Perfectly! Thank you very much! This is the solution to my problem.

**Comment by StevenBonePgh** [comment]
@brendanzagaeski I was referred to here via your pull request to fix this issue via an issue I raised on [Developer Community](https://developercommunity2.visualstudio.com/t/xamarinandroid-missing-resourceid-fields/1238590) that produces similar compiler errors. I included binary build logs in that issue.

In the process of researching I found this issue, resolution, and workaround but it does not appear to fit my case. Unfortunately, Theresa Zhang marked this as cause of reported issue - if it is I certainly do not understand how. As I would prefer to keep the logs private, is it possible for you to review logs added there?  If this issue is in fact the cause, would we be able to lobby again to get your pull request integrated as it is over a year old?  

Thanks!

**Comment by brendanzagaeski** [comment]
Thanks for bringing Developer Community item to my attention, StevenBonePgh. Indeed, it doesn't look related to this old issue. I've now reopened that new Developer Community item for further consideration.
