### ISSUE TITLE
HTTPClient in Android Behaviour Differently in VS2019 and VS2017 with Linker Enabled

### ISSUE THREAD

**Issue by ooikengsiang** [xamarin/xamarin-android#2993]
### Steps to Reproduce
1. Compile an Android project with HTTPClient with Android HttpClient implementation calling https end-point through VS2019 in release mode with linker enabled.
2. Run the app in Android 4.4 emulator.
3. HTTPClient call failed.

### Expected Behavior
Android project compiled with VS2017 in release mode with linker enabled.
HttpClient implementation use Android.
HTTPClient work when calling https end-point running in Android 4.4 emulator.
Same project compiled with VS2019 in release mode with linker enabled.
Expected HTTPClient to work normally.

### Actual Behavior
HTTPClient doesn't work when compiled VS2019 in release mode with linker enabled when running in Android 4.4 emulator.
OldAndroidSSLSocketFactory class not found exception is throw instead.

### Version Information
Visual Studio 2019 (16.0.1) with Xamarin.Android SDK 9.2.0.5
Visual Studio 2017 (15.9.8) with Xamarin.Android SDK 9.1.7.0

### Device Log
{Java.Lang.NoClassDefFoundError: xamarin/android/net/OldAndroidSSLSocketFactory ---> Java.Lang.ClassNotFoundException: Didn't find class "xamarin.android.net.OldAndroidSSLSocketFactory" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/system/lib]]
   --- End of inner exception stack trace ---
  at Java.Interop.JniEnvironment+Types.FindClass (System.String classname) [0x00114] in <6838b1f2b3414511b059ec03565114ce>:0 
  at Java.Interop.JniType..ctor (System.String classname) [0x00006] in <6838b1f2b3414511b059ec03565114ce>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods..ctor (System.Type declaringType) [0x0005b] in <6838b1f2b3414511b059ec03565114ce>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.GetConstructorsForType (System.Type declaringType) [0x00031] in <6838b1f2b3414511b059ec03565114ce>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.StartCreateInstance (System.String constructorSignature, System.Type declaringType, Java.Interop.JniArgumentValue* parameters) [0x00038] in <6838b1f2b3414511b059ec03565114ce>:0 
  at Javax.Net.Ssl.SSLSocketFactory..ctor () [0x00034] in <6f7c932c080044dbbeecffc809d59bba>:0 
  at Xamarin.Android.Net.OldAndroidSSLSocketFactory..ctor () [0x00010] in <6f7c932c080044dbbeecffc809d59bba>:0 
  at Xamarin.Android.Net.AndroidClientHandler.SetupSSL (Javax.Net.Ssl.HttpsURLConnection httpsConnection) [0x00027] in <6f7c932c080044dbbeecffc809d59bba>:0 
  at Xamarin.Android.Net.AndroidClientHandler.SetupRequestInternal (System.Net.Http.HttpRequestMessage request, Java.Net.URLConnection conn) [0x0007b] in <6f7c932c080044dbbeecffc809d59bba>:0 
  at Xamarin.Android.Net.AndroidClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00236] in <6f7c932c080044dbbeecffc809d59bba>:0 
  at System.Net.Http.HttpClient.SendAsyncWorker (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption, System.Threading.CancellationToken cancellationToken) [0x000ca] in <3fc4898ec9544a7fb4aaef53939ca73e>:0 
  at AppName.GetProduct (System.String bearerToken, Card frontCard, Set set, System.Threading.CancellationToken cancellationToken) [0x000e8] in C:\Shared\Repos\AppName\AppName\AppName.Shared\Libraries\TCGPlayer\TCGPlayerAPI.cs:176 
  --- End of managed Java.Lang.NoClassDefFoundError stack trace ---
java.lang.NoClassDefFoundError: xamarin/android/net/OldAndroidSSLSocketFactory
	at dalvik.system.NativeStart.run(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class "xamarin.android.net.OldAndroidSSLSocketFactory" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	... 1 more

### Things I Tried.
- Same project compiled in VS2019 with linker enabled, HTTPClient work correctly in Android 6.0 emulator.
- Disable linker in VS2019, compile the same project, HTTPClient work correctly in Android 4.4 emulator.
- Add Xamarin.Android.Net.OldAndroidSSLSocketFactory into linker configuration file, compiled in VS2019 with linker enabled, HTTPClient still failed in Android 4.4 emulator.
- Same project compiled in VS2019 with linker enabled but change the HttpClient implementation to Managed, HTTPClient work correctly in Android 4.4 emulator.

**Comment by ooikengsiang** [comment]
I saw OldAndroidSSLSocketFactory was newly added in https://github.com/xamarin/xamarin-android/pull/2185 but I'm not sure if it was newly included in Xamarin.Android SDK 9.2.0.0 which caused this problem.

**Comment by radekdoulik** [comment]
Do you have possibly ProGuard enabled in the Release configuration?

Do you have an isolated test case, which reproduces the issue? That would help to make sure we look at the same problem.

**Comment by ooikengsiang** [comment]
> 
> 
> Do you have possibly ProGuard enabled in the Release configuration?
> 
> Do you have an isolated test case, which reproduces the issue? That would help to make sure we look at the same problem.

No Pro Guard.
I created a sample project: [https://1drv.ms/u/s!AsdINBY8jBXBn99o6x1soFIipdvRWg](https://1drv.ms/u/s!AsdINBY8jBXBn99o6x1soFIipdvRWg)
The error is lightly different but they are point to the same direction.

**Comment by radekdoulik** [comment]
Thank you for the sample. I have tried to reproduce meanwhile and run into different issue, which happens only in **Release** configuration. So it looks like there might be some parts linked away, indeed.

```
I/mono-stdout( 2673): Exception :System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: NameResolutionFailure
I/mono-stdout( 2673):   at System.Net.WebConnection+<Connect>d__16.MoveNext () [0x00044] in <82011ec060224fad81a1d4eba2b724fc>:0 
I/mono-stdout( 2673): --- End of stack trace from previous location where exception was thrown ---
I/mono-stdout( 2673):   at System.Net.WebConnection+<InitConnection>d__19.MoveNext () [0x000cc] in <82011ec060224fad81a1d4eba2b724fc>:0 
I/mono-stdout( 2673): --- End of stack trace from previous location where exception was thrown ---
I/mono-stdout( 2673):   at System.Net.WebOperation+<Run>d__57.MoveNext () [0x0009a] in <82011ec060224fad81a1d4eba2b724fc>:0 
I/mono-stdout( 2673): --- End of stack trace from previous location where exception was thrown ---
I/mono-stdout( 2673):   at System.Net.WebCompletionSource`1+<WaitForCompletion>d__15[T].MoveNext () [0x00094] in <82011ec060224fad81a1d4eba2b724fc>:0 
I/mono-stdout( 2673): --- End of stack trace from previous location where exception was thrown ---
I/mono-stdout( 2673):   at System.Net.HttpWebRequest+<RunWithTimeoutWorker>d__241`1[T].MoveNext () [0x000f8] in <82011ec060224fad81a1d4eba2b724fc>:0 
I/mono-stdout( 2673): --- End of stack trace from previous location where exception was thrown ---
I/mono-stdout( 2673):   at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00020] in <82011ec060224fad81a1d4eba2b724fc>:0 
I/mono-stdout( 2673):   at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.
Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <481029262c8c451c8b798975f0e9eb6c>:0 
I/mono-stdout( 2673): --- End of stack trace from previous location where exception was thrown ---
I/mono-stdout( 2673):   at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x0041d] in <4bed4e35b75e41c792b04d89e603e7a3>:0 
I/mono-stdout( 2673):    --- End of inner exception stack trace ---
I/mono-stdout( 2673):   at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x00478] in <4bed4e35b75e41c792b04d89e603e7a3>:0 
I/mono-stdout( 2673): --- End of stack trace from previous location where exception was thrown ---
I/mono-stdout( 2673):   at System.Net.Http.HttpClient+<SendAsyncWorker>d__49.MoveNext () [0x000ca] in <4bed4e35b75e41c792b04d89e603e7a3>:0 
I/mono-stdout( 2673): --- End of stack trace from previous location where exception was thrown ---
I/mono-stdout( 2673):   at test_httpclient.MainActivity+<TryHttpClient>d__0.MoveNext () [0x00091] in <1a686fef1902477cb8eca0842e6a4f10>:0 
```

I will try your sample next.

**Comment by radekdoulik** [comment]
@ooikengsiang I am unable to download the sample
```
This item might have been deleted, expired, or you might not have permission to view it. Contact the owner of this item for more information. 
```
I guess you might need to set permissions

**Comment by ooikengsiang** [comment]
> 
> 
> @ooikengsiang I am unable to download the sample
> 
> ```
> This item might have been deleted, expired, or you might not have permission to view it. Contact the owner of this item for more information. 
> ```
> 
> I guess you might need to set permissions

Sorry for the trouble, here are the link: [https://1drv.ms/u/s!AsdINBY8jBXBn99p2VzsGPDvFWB31A?e=JKePK3](https://1drv.ms/u/s!AsdINBY8jBXBn99p2VzsGPDvFWB31A?e=JKePK3)

**Comment by radekdoulik** [comment]
Thank you, it works now.

**Comment by softlion** [comment]
you could call `adb.exe shell setprop debug.mono.debug 1` to display android line numbers in the log stack strace. After the call, kill your android xamarin app and rerun.

Dunno why it's not by default in xamarin android.

**Comment by zoli13** [comment]
I have a Xamarin.Forms(3.6.0.220655) app, for both Android + iOS. 
**I can confirm,** I have issue with VS2019(16.0.2) + AOT(true) / LLVM(false -> this again a bug in Xamarin, set true makes app crash) + Release mode on Android 4.4 Device, when using HttpClient.
I don't have a callstack now, but it's about xamarin/android/net/OldAndroidSSLSocketFactory

**Comment by ea-orbital8** [comment]
I experienced the same error for a release mode project with linker and proguard enabled built using VS2019 v16.1.0 (and earlier VS2019 releases). I was able to resolve by adding the following to my linker.xml file.

```  
<assembly fullname="Mono.Android">
    <namespace fullname="Xamarin.Android.Net" />
</assembly>
```

I also found I had to add the following to my proguard.cfg, although I am not entirely sure all these changes were needed
```
-keep class mono.java.** { *; <init>(...); }
-keep class mono.javax.** { *; <init>(...); }
-keep class xamarin.android.** { *; <init>(...); }
```

**Comment by zoli13** [comment]
> I experienced the same error for a release mode project with linker and proguard enabled built using VS2019 v16.1.0 (and earlier VS2019 releases). I was able to resolve by adding the following to my linker.xml file.

I tried, added XML data to my LinkDescription file, and also extended my proguard-android.txt with those 3 lines. 

**Still not working on my Nexus7 4.4, but at least now I have different error messages, like:**
_Couldn't bind to method 'GetGetDefaultCipherSuitesHandler'_ 
and
_Native method not found: xamarin,android.net.OldAndroidSSLSocketFactory.n_createSocket:(Ljava/net/Socket;Ljava/lang/String;IZ)Ljava/net/Socket;_

**Comment by ooikengsiang** [comment]
I'm current workaround is to use VS2017 to generate the package until all issue resolved.

**Comment by ea-orbital8** [comment]
@zoli13 I also had to obliterate my bin an obj folders between each build to test this when working on my proguard and linker configs. I think I got the `Couldn't bind to method 'GetGetDefaultCipherSuitesHandler'` error message when I was missing `-keep class mono.javax.** { *; <init>(...); }` in the proguard.cfg.

**Comment by softlion** [comment]
On my side, when selecting the Android HttpClient, no http call are ever made. I am forced to use the .net http client. It was working back in VS2017.

**Comment by raviventium** [comment]
> I experienced the same error for a release mode project with linker and proguard enabled built using VS2019 v16.1.0 (and earlier VS2019 releases). I was able to resolve by adding the following to my linker.xml file.
> 
> ```
> <assembly fullname="Mono.Android">
>     <namespace fullname="Xamarin.Android.Net" />
> </assembly>
> ```
> 
> I also found I had to add the following to my proguard.cfg, although I am not entirely sure all these changes were needed
> 
> ```
> -keep class mono.java.** { *; <init>(...); }
> -keep class mono.javax.** { *; <init>(...); }
> -keep class xamarin.android.** { *; <init>(...); }
> ```

This worked for me as well.
Since i do not use pro-guard  only the linker file was needed.

**Comment by gameleon-dev** [comment]
Adding the proguard rules and linker.xml rules solved the issue for me.

Only the `-keep class xamarin.android.** { *; <init>(...); }` line was needed for the ProGuard file.

**Comment by claudioredi** [comment]
Having **a lot** of users with this same error myself... for now I'm using `HttpClientHandler` in Android for API version <= 20... this is not ideal at all though...

**Comment by wislon** [comment]
I only needed to add the line to the `linker.xml` file, since the project I'm working on hasn't got any proguard-related stuff explicitly turned on in it. Thanks so much for this! 👍

**Comment by Strifex** [comment]
Just wanted to state - I had a similar issue using VS16.3.1 - reading content from the httprequest from the httpclient (both string or stream) would return garbled bytes instead of a proper json string.  This problem only occurred using the AndroidHttpClient in Release Mode with "Link SDK Assemblies" turned on.  As soon as I added the custom linker file as stated above (to stop linking away Xamarin.Android.Net) everything worked as expected.

**Comment by radekdoulik** [comment]
I think this is duplicate of https://github.com/xamarin/xamarin-android/issues/3626

**Comment by Digifais** [comment]
@radekdoulik Can confirm this isn't fixed with the latest preview on VS for Mac as mentioned in #3626

**Comment by radekdoulik** [comment]
@Digifais could you please attach project which reproduces the problem? what preview version do you use?

**Comment by Digifais** [comment]
> @Digifais could you please attach project which reproduces the problem? what preview version do you use?

I'll get in touch with you on Gitter.

**Comment by ssotir** [comment]
I've tried the following linker.xml file with success.

<linker>
  <assembly fullname="Mono.Android">
    <type fullname="Xamarin.Android.Net.OldAndroidSSLSocketFactory" preserve="all"/>
  </assembly>
</linker>

**Comment by ElryWeeb** [comment]
5 years later and still nothing, microsoft fucking sucks

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
