### ISSUE TITLE
Different compilation issues after upgrading Xamarin.Android to 10.1.x.x

### ISSUE THREAD

**Issue by claudioredi** [xamarin/xamarin-android#4164]
### Steps to Reproduce

1. Upgraded to 10.1.x.x (I'm sure I've seen this first time after upgrading on preview channel to 10.1.0.30 or 10.1.1.0)
2. Compiled the project (cleaned, deleted bin / obj, etc)

### Expected Behavior
The project should compile without errors

### Actual Behavior

I got a compilation error

**/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3,3): Error: error XA4212: Type `Android.Support.Design.Widget.CheckableImageButton` implements `Android.Runtime.IJavaObject` but does not inherit `Java.Lang.Object` or `Java.Lang.Throwable`. This is not supported. (FishAngler.Droid)**

I'm not sure what action I can take here so instead of trying to fix it, I swallowed the error using the following project setting

```<AndroidErrorOnCustomJavaObject>false</AndroidErrorOnCustomJavaObject>```

After using that the compilation error disappears but I get another 20 new ones

<pre>
(_CompileJava target) -> 
  obj/Debug/android/src/mono/android/support/v7/internal/widget/FitWindowsViewGroup_OnFitSystemWindowsListenerImplementor.java(8,57): javac error JAVAC0000:  error: package android.support.v7.internal.widget.FitWindowsViewGroup does not exist 
obj/Debug/android/src/mono/android/support/v7/internal/widget/FitWindowsViewGroup_OnFitSystemWindowsListenerImplementor.java(8,57): javac error JAVAC0000: 		android.support.v7.internal.widget.FitWindowsViewGroup.OnFitSystemWindowsListener 
obj/Debug/android/src/mono/android/support/v7/internal/widget/FitWindowsViewGroup_OnFitSystemWindowsListenerImplementor.java(8,57): javac error JAVAC0000:  
  obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemClickListenerImplementor.java(8,55): javac error JAVAC0000:  error: package android.support.v7.internal.widget.AdapterViewCompat does not exist 
obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemClickListenerImplementor.java(8,55): javac error JAVAC0000: 		android.support.v7.internal.widget.AdapterViewCompat.OnItemClickListener 
obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemClickListenerImplementor.java(8,55): javac error JAVAC0000:  
  obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemClickListenerImplementor.java(28,61): javac error JAVAC0000:  error: package android.support.v7.internal.widget does not exist 
obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemClickListenerImplementor.java(28,61): javac error JAVAC0000: 	public void onItemClick (android.support.v7.internal.widget.AdapterViewCompat p0, android.view.View p1, int p2, long p3) 
obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemClickListenerImplementor.java(28,61): javac error JAVAC0000:  
  obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemClickListenerImplementor.java(33,71): javac error JAVAC0000:  error: package android.support.v7.internal.widget does not exist 
obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemClickListenerImplementor.java(33,71): javac error JAVAC0000: 	private native void n_onItemClick (android.support.v7.internal.widget.AdapterViewCompat p0, android.view.View p1, int p2, long p3); 
obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemClickListenerImplementor.java(33,71): javac error JAVAC0000:  
  obj/Debug/android/src/mono/android/support/v7/internal/widget/ViewStubCompat_OnInflateListenerImplementor.java(8,52): javac error JAVAC0000:  error: package android.support.v7.internal.widget.ViewStubCompat does not exist 
obj/Debug/android/src/mono/android/support/v7/internal/widget/ViewStubCompat_OnInflateListenerImplementor.java(8,52): javac error JAVAC0000: 		android.support.v7.internal.widget.ViewStubCompat.OnInflateListener 
obj/Debug/android/src/mono/android/support/v7/internal/widget/ViewStubCompat_OnInflateListenerImplementor.java(8,52): javac error JAVAC0000:  
  obj/Debug/android/src/mono/android/support/v7/internal/widget/ViewStubCompat_OnInflateListenerImplementor.java(28,59): javac error JAVAC0000:  error: package android.support.v7.internal.widget does not exist 
obj/Debug/android/src/mono/android/support/v7/internal/widget/ViewStubCompat_OnInflateListenerImplementor.java(28,59): javac error JAVAC0000: 	public void onInflate (android.support.v7.internal.widget.ViewStubCompat p0, android.view.View p1) 
obj/Debug/android/src/mono/android/support/v7/internal/widget/ViewStubCompat_OnInflateListenerImplementor.java(28,59): javac error JAVAC0000:  
  obj/Debug/android/src/mono/android/support/v7/internal/widget/ViewStubCompat_OnInflateListenerImplementor.java(33,69): javac error JAVAC0000:  error: package android.support.v7.internal.widget does not exist 
obj/Debug/android/src/mono/android/support/v7/internal/widget/ViewStubCompat_OnInflateListenerImplementor.java(33,69): javac error JAVAC0000: 	private native void n_onInflate (android.support.v7.internal.widget.ViewStubCompat p0, android.view.View p1); 
obj/Debug/android/src/mono/android/support/v7/internal/widget/ViewStubCompat_OnInflateListenerImplementor.java(33,69): javac error JAVAC0000:  
  obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemLongClickListenerImplementor.java(8,55): javac error JAVAC0000:  error: package android.support.v7.internal.widget.AdapterViewCompat does not exist 
obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemLongClickListenerImplementor.java(8,55): javac error JAVAC0000: 		android.support.v7.internal.widget.AdapterViewCompat.OnItemLongClickListener 
obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemLongClickListenerImplementor.java(8,55): javac error JAVAC0000:  
  obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemLongClickListenerImplementor.java(28,68): javac error JAVAC0000:  error: package android.support.v7.internal.widget does not exist 
obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemLongClickListenerImplementor.java(28,68): javac error JAVAC0000: 	public boolean onItemLongClick (android.support.v7.internal.widget.AdapterViewCompat p0, android.view.View p1, int p2, long p3) 
obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemLongClickListenerImplementor.java(28,68): javac error JAVAC0000:  
  obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemLongClickListenerImplementor.java(33,78): javac error JAVAC0000:  error: package android.support.v7.internal.widget does not exist 
obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemLongClickListenerImplementor.java(33,78): javac error JAVAC0000: 	private native boolean n_onItemLongClick (android.support.v7.internal.widget.AdapterViewCompat p0, android.view.View p1, int p2, long p3); 
obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemLongClickListenerImplementor.java(33,78): javac error JAVAC0000:  
  obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemSelectedListenerImplementor.java(8,55): javac error JAVAC0000:  error: package android.support.v7.internal.widget.AdapterViewCompat does not exist 
obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemSelectedListenerImplementor.java(8,55): javac error JAVAC0000: 		android.support.v7.internal.widget.AdapterViewCompat.OnItemSelectedListener 
obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemSelectedListenerImplementor.java(8,55): javac error JAVAC0000:  
  obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemSelectedListenerImplementor.java(29,64): javac error JAVAC0000:  error: package android.support.v7.internal.widget does not exist 
obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemSelectedListenerImplementor.java(29,64): javac error JAVAC0000: 	public void onItemSelected (android.support.v7.internal.widget.AdapterViewCompat p0, android.view.View p1, int p2, long p3) 
obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemSelectedListenerImplementor.java(29,64): javac error JAVAC0000:  
  obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemSelectedListenerImplementor.java(34,74): javac error JAVAC0000:  error: package android.support.v7.internal.widget does not exist 
obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemSelectedListenerImplementor.java(34,74): javac error JAVAC0000: 	private native void n_onItemSelected (android.support.v7.internal.widget.AdapterViewCompat p0, android.view.View p1, int p2, long p3); 
obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemSelectedListenerImplementor.java(34,74): javac error JAVAC0000:  
  obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemSelectedListenerImplementor.java(37,67): javac error JAVAC0000:  error: package android.support.v7.internal.widget does not exist 
obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemSelectedListenerImplementor.java(37,67): javac error JAVAC0000: 	public void onNothingSelected (android.support.v7.internal.widget.AdapterViewCompat p0) 
obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemSelectedListenerImplementor.java(37,67): javac error JAVAC0000:  
  obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemSelectedListenerImplementor.java(42,77): javac error JAVAC0000:  error: package android.support.v7.internal.widget does not exist 
obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemSelectedListenerImplementor.java(42,77): javac error JAVAC0000: 	private native void n_onNothingSelected (android.support.v7.internal.widget.AdapterViewCompat p0); 
obj/Debug/android/src/mono/android/support/v7/internal/widget/AdapterViewCompat_OnItemSelectedListenerImplementor.java(42,77): javac error JAVAC0000:  
  obj/Debug/android/src/mono/android/support/v7/internal/widget/ActivityChooserModel_OnChooseActivityListenerImplementor.java(8,58): javac error JAVAC0000:  error: package android.support.v7.internal.widget.ActivityChooserModel does not exist 
obj/Debug/android/src/mono/android/support/v7/internal/widget/ActivityChooserModel_OnChooseActivityListenerImplementor.java(8,58): javac error JAVAC0000: 		android.support.v7.internal.widget.ActivityChooserModel.OnChooseActivityListener 
obj/Debug/android/src/mono/android/support/v7/internal/widget/ActivityChooserModel_OnChooseActivityListenerImplementor.java(8,58): javac error JAVAC0000:  
  obj/Debug/android/src/mono/android/support/v7/internal/widget/ActivityChooserModel_OnChooseActivityListenerImplementor.java(28,69): javac error JAVAC0000:  error: package android.support.v7.internal.widget does not exist 
obj/Debug/android/src/mono/android/support/v7/internal/widget/ActivityChooserModel_OnChooseActivityListenerImplementor.java(28,69): javac error JAVAC0000: 	public boolean onChooseActivity (android.support.v7.internal.widget.ActivityChooserModel p0, android.content.Intent p1) 
obj/Debug/android/src/mono/android/support/v7/internal/widget/ActivityChooserModel_OnChooseActivityListenerImplementor.java(28,69): javac error JAVAC0000:  
  obj/Debug/android/src/mono/android/support/v7/internal/widget/ActivityChooserModel_OnChooseActivityListenerImplementor.java(33,79): javac error JAVAC0000:  error: package android.support.v7.internal.widget does not exist 
obj/Debug/android/src/mono/android/support/v7/internal/widget/ActivityChooserModel_OnChooseActivityListenerImplementor.java(33,79): javac error JAVAC0000: 	private native boolean n_onChooseActivity (android.support.v7.internal.widget.ActivityChooserModel p0, android.content.Intent p1); 
obj/Debug/android/src/mono/android/support/v7/internal/widget/ActivityChooserModel_OnChooseActivityListenerImplementor.java(33,79): javac error JAVAC0000:  
</pre>

### Version Information

The app targets api 29. We didn't migrated to Androidx so we keep referencing support libraries 28.0.0.x... tried to target api 28 to see if this inconsistency was causing the problem, it didn't help

<pre>
=== Visual Studio Community 2019 for Mac ===

Version 8.4.2 (build 59)
Installation UUID: cc83228b-b085-497a-875f-63674db0e3c2
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.25 (issue-7441-d16-3-vsmac / 881172e73)

	Package version: 606000155

=== Mono Framework MDK ===

Runtime:
	Mono 6.6.0.155 (2019-08/296a9afdb24) (64-bit)
	Package version: 606000155

=== Roslyn (Language Service) ===

3.4.0-beta4-19562-05+ff930dec4565e2bc424ad3bf3e22ecb20542c87d

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.100/Sdks
SDK Versions:
	3.1.100
	3.0.100
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.4
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.0
	3.0.0
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.2
	1.1.1
	1.0.5
	1.0.4

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 10.1.3.7 (Visual Studio Community)
Commit: xamarin-android/d16-4/d66aed0
Android SDK: /Users/claudioredi/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.1
SDK Build Tools Version: 29.0.0

Build Information: 
Mono: fd9f379
Java.Interop: xamarin/java.interop/d16-4@c4e569f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/claudioredi/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.4.0.9
Hash: 3f7256f
Branch: remotes/origin/d16-4
Build date: 2020-01-14 22:19:04 UTC

=== Android Device Manager ===

Version: 16.4.0.30
Hash: f9172e2
Branch: remotes/origin/d16-4
Build date: 2020-01-14 22:19:24 UTC

=== Xamarin Designer ===

Version: 16.4.0.478
Hash: 95f0ab363
Branch: remotes/origin/d16-4
Build date: 2020-01-08 23:59:46 UTC

=== Apple Developer Tools ===

Xcode 11.3 (15712)
Build 11C29

=== Xamarin.Mac ===

Version: 6.10.0.17 (Visual Studio Community)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500

=== Xamarin.iOS ===

Version: 13.10.0.17 (Visual Studio Community)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 804020059
Git revision: eb6fcdd83a227678e487aa733df3c8745f54fafc
Build date: 2020-01-17 12:12:02+00
Build branch: release-8.4
Xamarin extensions: ec32c90978c94f03d72f507b01f5aee70952ce87

=== Operating System ===

Mac OS X 10.15.0
Darwin 19.0.0 Darwin Kernel Version 19.0.0
    Wed Sep 25 20:18:50 PDT 2019
    root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64
</pre>

### Log File

[build_log.txt](https://github.com/xamarin/xamarin-android/files/4104611/build_log.txt)
Attached build log.

**Comment by claudioredi** [comment]
Do you have any idea about what could be causing this? It's preventing us to upgrade to Xamarin.Android 10.1.X and there are different features included on that release that we'd love to try.

**Comment by jonathanpeppers** [comment]
@claudioredi it doesn't look like the build log is diagnostic verbosity, can you attach a diagnostic log?

https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output

Also, could you paste the list of NuGet packages you are using in your project? Thanks!

**Comment by jonathanpeppers** [comment]
Looking at the class it's complaining about (downloaded the [NuGet package](https://www.nuget.org/packages/Xamarin.Android.Support.Design/28.0.0.3)):
```csharp
[Register("android/support/design/widget/CheckableImageButton", DoNotGenerateAcw = true)]
public class CheckableImageButton : AppCompatImageButton, ICheckable, IJavaObject, IDisposable
```
It seems like it should be OK and not hit the error it's giving you?

Reviewing the code that generates the error/warning it should count as a `Java.Lang.Object` subclass, weird:

https://github.com/xamarin/java.interop/blob/ad0aa2007d6b6f0ed94dafe21a1ed0fa42ee09e2/src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaTypeScanner.cs#L45-L56

@jonpryor  @jpobst do you know anything that changed in 16.4 that could cause this? The code above was last changed ~2 years ago.

**Comment by jpobst** [comment]
I'm not aware of anything that changed around this.  I wonder if it's just an issue with Cecil being able to resolve all the assemblies needed to get down to the base JLO reference.

You might want to try clearing the Nuget cache to see if something there got in a bad state.

**Comment by claudioredi** [comment]
@jgold6 : it happened to multiple developers in my team after upgrading to Xamarin.Android 10.1.x. I'm not the only seeing that. If you downgrade, it compiles correctly again. Will see if we find something on our side but this problem definiitvely triggered by the upgrade.

**Comment by jonathanpeppers** [comment]
@claudioredi I was getting some warnings with your list of NuGet packages:
```
NU1608: Detected package version outside of dependency constraint: Xamarin.Android.Arch.Core.Common 1.1.1.1 requires Xamarin.Android.Support.Annotations (= 28.0.0.1) but version Xamarin.Android.Support.Annotations 28.0.0.3 was resolved.
NU1608: Detected package version outside of dependency constraint: Xamarin.Android.Arch.Core.Runtime 1.1.1.1 requires Xamarin.Android.Support.Annotations (= 28.0.0.1) but version Xamarin.Android.Support.Annotations 28.0.0.3 was resolved.
NU1608: Detected package version outside of dependency constraint: Xamarin.Android.Arch.Lifecycle.Common 1.1.1.1 requires Xamarin.Android.Support.Annotations (= 28.0.0.1) but version Xamarin.Android.Support.Annotations 28.0.0.3 was resolved.
NU1608: Detected package version outside of dependency constraint: Xamarin.Android.Arch.Lifecycle.Runtime 1.1.1.1 requires Xamarin.Android.Support.Annotations (= 28.0.0.1) but version Xamarin.Android.Support.Annotations 28.0.0.3 was resolved.
NU1608: Detected package version outside of dependency constraint: Xamarin.Android.Arch.Lifecycle.ViewModel 1.1.1.1 requires Xamarin.Android.Support.Annotations (= 28.0.0.1) but version Xamarin.Android.Support.Annotations 28.0.0.3 was resolved.
```
Can you change all the `Xamarin.Android.Arch.*` packages to 1.1.1.3?

Then one other warning:
```
NU1605: Detected package downgrade: Xamarin.Firebase.Analytics from 71.1630.0 to 71.1606.0. Reference the package directly from the project to select a different version. 
```
I updated anything GooglePlayServices to `71.1630.0`.

After that I could build a sample project with these packages. Does getting everything on matching versions fix anything?

**Comment by claudioredi** [comment]
I didn't have time to go baack to this (I upgraded on a separated machine that I normally don't use). I don't believe that upgrading nuget packages will make a difference since I upgraded from 28.0.0.1 to 28.0.0.3 trying to get rid of the compilation issue. (it was originally 28.0.0.1).

Will try to generate a different test project trying to recreate this problem as obviously it's not ringing any bell for you guys so far.


Thanks!

**Comment by Flash3001** [comment]
We were able to get rid of the issue. 

On our .csproj we have a few <Reference Include="..."> for custom bindings and modified libraries. Within the folder those DLLs are stored there was a copy of **Xamarin.Android.Support.v4.dll** and **Xamarin.Android.Support.v7.AppCompat.dll**. Both bindings for 22.2.1.

Deleting both files allowed us to compile again using newer versions of Xamarin.Android.

We didn't have a direct <Reference ...> to those files in our .csproj as they were in there by mistake. 

It is still unclear why it compiled with version 1.0.0.6.2, but not with 1.0.1.3.7.

To add to this, with those files still present I was able to compile using 1.0.1.3.7 when unchecking "Use Shared Mono Runtime" and checking "Link SDK assemblies only".

On version 10.2.0.0.100 the previous approach didn't work as another error showed up (didn't investigate further).

If you want to investigate more on this issue I have attached a project you can use to reproduce it. It is basically a New Android project + 4 modified bindings + the 2 Android Support bindings +  Xamarin.Android.Support.v4 Nuget reference. 

[FailedCompilation.zip](https://github.com/xamarin/xamarin-android/files/4377326/FailedCompilation.zip)

**Comment by jpobst** [comment]
Android Support libraries are deprecated.  Hopefully this issue does not occur in AndroidX.
