### ISSUE TITLE
JDK 11 broke `@(JavaDocJar)` & related support

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#5474]
Context: https://github.com/xamarin/xamarin-android/pull/5468#issuecomment-756057167

Commit 380e95e340168f68b1ae3eb43e0a71b05bc6d80b inadvertently broken `@(JavaSourceJar)` and `@(JavaDocJar)` support.

### Steps to Reproduce

1. Try the repro at Issue #2745:
  a. Create a new Binding project.
  b. Download [`glide-3.7.0.jar`](https://github.com/bumptech/glide/releases/download/v3.7.0/glide-3.7.0.jar), set its Build action to `@(EmbeddedJar)`.
  c. Download [`glide-3.7.0-javadoc.jar`](https://github.com/bumptech/glide/releases/download/v3.7.0/glide-3.7.0-javadoc.jar), set its Build action to `@(JavaDocJar)`
3. Build the project.

[Scratch.Gxa2745.zip](https://github.com/xamarin/xamarin-android/files/5783292/Scratch.Gxa2745.zip)

### Expected Behavior

The build should *use* the `@(JavaDocJar)` file.  (Not necessarily "build successfully", but "do something with" the `@(JavaDocJar)` files.

### Actual Behavior

The `@(JavaDocJar)` file isn't used.

Issue #2745 makes for an interesting comparison point: if the file were used, the build would *fail* with an MSB3375, unless the underlying bug was fixed (PR #4406?!), which hasn't happened.

### Discussion

However, this is a *regression* introduced by the introduction of JDK 11 support in 380e95e340168f68b1ae3eb43e0a71b05bc6d80b, due to buggy JDK 1.8 detection.

If we build the project, we get binding-related errors:

```bash
$ msbuild /v:diag
…
BINDINGSGENERATOR : warning BG8604: top ancestor SupportRequestManagerFragment not found for nested type Com.Bumptech.Glide.Manager.SupportRequestManagerFragment._1.
…
obj/Debug/generated/src/Com.Bumptech.Glide.Load.Resource.Gif.GifResourceEncoder.cs(10,70): error CS0535: 'GifResourceEncoder' does not implement interface member 'IEncoder.
Encode(Object, Stream)' 
```

Sure, it errors, but at least we got to the point of building the binding!

However, if we "manually work around" the broken JDK 1.8 detection support by setting the `$(_JavadocSupported)` property to True, we in fact *reproduce* Issue #2745:

```bash
$ msbuild /p:_JavadocSupported=True /v:diag
…
…/Xamarin.Android.Bindings.Documentation.targets(31,5): error MSB3375: The file "obj/Debug/javadocs/glide-3.7.0-javadoc.stamp" does not exist. 
```

This proves three things:

1. Commit 380e95e3 broke "out-of-the-box" `$(JavaDocJar)` support.
2. Issue #2745 has not *actually* been fixed
2. `generator` output remains "less-than-ideal"

**Comment by jonpryor** [comment]
What's "funny" is a7413a2389886082c3d3422c50a7e6cc84f43d8f *removes* the `$(_JavadocSupported)` property, so the "workaround to force Issue #2745 to occur" no longer works.

And Issue #2745 doesn't appear.

But, again, that's *not* because it's been fixed.  It's because we seem to have *broken* `@(JavaDocJar)` support entirely, *probably* because of a7413a2389886082c3d3422c50a7e6cc84f43d8f.

On the plus side, `@(JavaSourceJar)` support is *much* better: drop in [`glide-3.7.0-sources.jar`](https://github.com/bumptech/glide/releases/download/v3.7.0/glide-3.7.0-sources.jar) with a Build action of `@(JavaSourceJar)` in current master, and the resulting binding will contain *C# XML Documentation Comments*:

```csharp
// File: obj/Debug/generated/src/Com.Bumptech.Glide.Manager.ILifecycle.cs

namespace Com.Bumptech.Glide.Manager {

	/// <summary>An interface for listening to Activity/Fragment lifecycle events.</summary>
	// Metadata.xml XPath interface reference: path="/api/package[@name='com.bumptech.glide.manager']/interface[@name='Lifecycle']"
	[Register ("com/bumptech/glide/manager/Lifecycle", "", "Com.Bumptech.Glide.Manager.ILifecycleInvoker")]
	public partial interface ILifecycle : IJavaObject, IJavaPeerable {
		// Metadata.xml XPath method reference: path="/api/package[@name='com.bumptech.glide.manager']/interface[@name='Lifecycle']/method[@name='addListener' and count(parameter)=1 and parameter[1][@type='com.bumptech.glide.manager.LifecycleListener']]"
		/// <summary>Adds the given listener to the set of listeners managed by this Lifecycle implementation.</summary>
		[Register ("addListener", "(Lcom/bumptech/glide/manager/LifecycleListener;)V", "GetAddListener_Lcom_bumptech_glide_manager_LifecycleListener_Handler:Com.Bumptech.Glide.Manager.ILifecycleInvoker, Scratch.Gxa2745")]
		void AddListener (global::Com.Bumptech.Glide.Manager.ILifecycleListener listener);

	}
}
```

which is *really cool*.

…but doesn't change the fact that `@(JavaDocJar)` is currently broken. 😞

**Comment by jonpryor** [comment]
I can cause Issue #2745 on 0f2dc44791da610e6dd9994c9f1c781f23c4f7f2 by building with `/p:_UseLegacyJavadocImport=True`.
